"""Pydantic models for API request/response schemas."""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime


class QueryRequest(BaseModel):
    """Request body for SQL generation endpoint."""

    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Natural language query"
    )


class SQLGenerationResponse(BaseModel):
    """Response from SQL generation endpoint."""

    status: str = Field(..., description="success or error")
    sql_query: Optional[str] = Field(None, description="Generated SQL query")
    original_request: Optional[str] = Field(None, description="Original user request")
    is_valid: bool = Field(..., description="Whether SQL is valid")
    error: Optional[str] = Field(None, description="Error message if failed")
    tokens_used: int = Field(default=0, description="Tokens used in API call")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class SQLExecutionRequest(BaseModel):
    """Request body for SQL execution endpoint."""

    sql_query: str = Field(..., min_length=1, description="SQL query to execute")


class ExecutionResult(BaseModel):
    """Result of SQL execution."""

    timestamp: datetime
    status: str
    rows_returned: int
    columns: List[str]
    sample_data: List[Dict[str, Any]]


class TestGenerationRequest(BaseModel):
    """Request body for test generation endpoint."""

    sql_query: str = Field(..., min_length=1, description="SQL query to generate tests for")
    user_request: Optional[str] = Field(None, description="Original user request for context")


class TestGenerationResponse(BaseModel):
    """Response from test generation endpoint."""

    status: str = Field(..., description="success or error")
    test_code: Optional[str] = Field(None, description="Generated pytest code")
    test_output: Optional[str] = Field(None, description="Pytest execution output")
    exit_code: Optional[int] = Field(None, description="Test exit code")
    test_file: Optional[str] = Field(None, description="Path to saved test file")
    error: Optional[str] = Field(None, description="Error message if failed")
    tokens_used: int = Field(default=0, description="Tokens used in API call")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class FullPipelineRequest(BaseModel):
    """Request body for full pipeline endpoint."""

    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Natural language query"
    )


class FullPipelineResponse(BaseModel):
    """Response from full pipeline endpoint."""

    status: str = Field(..., description="success or error")
    query: str = Field(..., description="Original query")
    final_status: Optional[str] = Field(None, description="Summary of execution")
    phases: Dict[str, Any] = Field(..., description="Results from each phase")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = Field(..., description="healthy or unhealthy")
    service: str = Field(..., description="Service name")
    version: str = Field(..., description="Service version")


class ReadyResponse(BaseModel):
    """Readiness check response."""

    status: str = Field(..., description="ready or not ready")
    api_key_configured: bool = Field(..., description="Whether API key is configured")
    model: str = Field(..., description="LLM model being used")


class ErrorResponse(BaseModel):
    """Generic error response."""

    error: str = Field(..., description="Error message")
    type: str = Field(..., description="Error type")
    request_id: Optional[str] = Field(None, description="Request ID for tracing")
    details: Optional[Dict[str, Any]] = Field(None, description="Additional error details")


class AgentRefineSqlRequest(BaseModel):
    """Request body for SQL refinement agent endpoint."""

    initial_query: str = Field(..., description="Original natural language query")
    generated_sql: str = Field(..., description="SQL generated by LLM")
    validation_feedback: str = Field(..., description="Feedback for refinement")


class AgentRefineSqlResponse(BaseModel):
    """Response from SQL refinement agent endpoint."""

    conversation_id: str = Field(..., description="Unique conversation ID")
    original_sql: str = Field(..., description="Original generated SQL")
    refined_sql: str = Field(..., description="Refined SQL after agent analysis")
    reasoning: str = Field(..., description="Agent's reasoning for refinement")
    tokens_used: int = Field(..., description="Tokens used in agent conversation")
    turns: int = Field(default=1, description="Number of conversation turns")


class AgentValidateTestsRequest(BaseModel):
    """Request body for test validation agent endpoint."""

    sql_query: str = Field(..., description="SQL query being tested")
    test_code: str = Field(..., description="Generated pytest code")
    test_output: str = Field(..., description="Output from test execution")


class AgentValidateTestsResponse(BaseModel):
    """Response from test validation agent endpoint."""

    conversation_id: str = Field(..., description="Unique conversation ID")
    original_tests: str = Field(..., description="Original test code")
    improved_tests: str = Field(..., description="Improved test code from agent")
    suggestions: str = Field(..., description="Agent's suggestions for improvement")
    tokens_used: int = Field(..., description="Tokens used in agent conversation")


class AgentOptimizeQueryRequest(BaseModel):
    """Request body for query optimization agent endpoint."""

    sql_query: str = Field(..., description="SQL query to optimize")
    performance_metrics: Optional[Dict[str, Any]] = Field(
        None,
        description="Performance metrics (query_time_ms, rows_scanned, etc.)"
    )


class AgentOptimizeQueryResponse(BaseModel):
    """Response from query optimization agent endpoint."""

    conversation_id: str = Field(..., description="Unique conversation ID")
    original_query: str = Field(..., description="Original SQL query")
    optimized_query: str = Field(..., description="Optimized SQL from agent")
    suggestions: str = Field(..., description="Agent's optimization suggestions")
    tokens_used: int = Field(..., description="Tokens used in agent conversation")
